import type { BankRateSource } from "../types";
import { BANK_RATE_SOURCES } from "../../shared/bankRateSources.js";

/* v6 bank source snapshot. The shared master below is authoritative.
const legacyBankRateSources: BankRateSource[] = [
  {
    id: "momiji",
    bankName: "もみじ銀行",
    productName: "YCG住宅ローン（融資手数料型）",
    rateUrl: "https://www.momijibank.co.jp/personal/borrow/house/tesuuryougata/",
    insuranceUrl: "https://www.momijibank.co.jp/personal/borrow/house/tesuuryougata/",
    ratePurpose: "current-bank-lower-rate-check",
    compareType: "new-or-refinance-reference",
    targetRateType: "variable",
    cancerInsuranceTarget: "がん100%込み",
    note: "現在銀行。下限金利と自分の適用金利を比較し、交渉判定に使う",
  },
  {
    id: "mufg",
    bankName: "三菱UFJ銀行",
    productName: "住宅ローン",
    rateUrl: "https://www.bk.mufg.jp/kariru/jutaku/yuuguu/index.html",
    insuranceUrl: "https://www.bk.mufg.jp/kariru/jutaku/hoken/shippei/index.html",
    ratePurpose: "refinance-comparison",
    compareType: "refinance-or-new-reference",
    targetRateType: "variable",
    cancerInsuranceTarget: "疾病保障プラン要確認",
    note: "金利ページと疾病保障ページを分けて確認する",
  },
  {
    id: "smbc",
    bankName: "三井住友銀行",
    productName: "住宅ローン",
    rateUrl: "https://www.smbc.co.jp/kojin/jutaku_loan/kinri/",
    insuranceUrl: "https://www.smbc.co.jp/kojin/jutaku_loan/reason/shippei_20-46.html",
    ratePurpose: "refinance-comparison",
    compareType: "refinance-comparison",
    targetRateType: "variable",
    cancerInsuranceTarget: "8大疾病保障要確認",
    note: "金利と疾病保障を別URLで確認する",
  },
  {
    id: "mizuho",
    bankName: "みずほ銀行",
    productName: "住宅ローン / 借り換え住宅ローン",
    rateUrl: "https://www.mizuhobank.co.jp/loan_housing/housingloancost/index.html",
    insuranceUrl: "https://www.mizuhobank.co.jp/loan_housing/lineup/refinanced_lineup/index.html",
    ratePurpose: "refinance-comparison",
    compareType: "refinance-comparison",
    targetRateType: "variable",
    cancerInsuranceTarget: "要確認",
    note: "金利一覧ページを主URL、借換え商品概要を補助URLとして扱う",
  },
  {
    id: "resona",
    bankName: "りそな銀行",
    productName: "住宅ローン（借り換え）",
    rateUrl: "https://www.resonabank.co.jp/kojin/jutaku/karikae/",
    insuranceUrl: "https://www.resonabank.co.jp/kojin/jutaku/karikae/",
    ratePurpose: "refinance-comparison",
    compareType: "refinance-comparison",
    targetRateType: "variable",
    cancerInsuranceTarget: "要確認",
    note: "借換えページを主確認URLにする",
  },
  {
    id: "netbk",
    bankName: "住信SBIネット銀行",
    productName: "住宅ローン",
    rateUrl: "https://www.netbk.co.jp/contents/lp/homeloan/web/re.html",
    insuranceUrl: "https://www.netbk.co.jp/contents/lineup/home-loan/danshin/",
    ratePurpose: "refinance-comparison",
    compareType: "refinance-comparison",
    targetRateType: "variable",
    cancerInsuranceTarget: "3大疾病50など要補正",
    note: "スゴ団信の保障内容を別URLで確認する",
  },
  {
    id: "jibun",
    bankName: "auじぶん銀行",
    productName: "住宅ローン",
    rateUrl: "https://www.jibunbank.co.jp/products/homeloan/interest/",
    insuranceUrl: "https://www.jibunbank.co.jp/products/homeloan/insurance/",
    ratePurpose: "refinance-comparison",
    compareType: "refinance-comparison",
    targetRateType: "variable",
    cancerInsuranceTarget: "がん50 / がん100を区別",
    note: "長期返済上乗せ、借入割合上乗せ、団信上乗せを補正する",
  },
  {
    id: "paypay",
    bankName: "PayPay銀行",
    productName: "住宅ローン",
    rateUrl: "https://www.paypay-bank.co.jp/mortgage/interest/index.html",
    insuranceUrl: "https://www.paypay-bank.co.jp/mortgage/insurance/index.html",
    ratePurpose: "refinance-comparison",
    compareType: "refinance-comparison",
    targetRateType: "variable",
    cancerInsuranceTarget: "がん100など要確認",
    note: "団信プランによる金利上乗せを補正する",
  },
  {
    id: "sbishinsei",
    bankName: "SBI新生銀行",
    productName: "住宅ローン",
    rateUrl: "https://www.sbishinseibank.co.jp/retail/housing/interest/floating/",
    insuranceUrl: "https://www.sbishinseibank.co.jp/retail/housing/insurance.html",
    ratePurpose: "refinance-comparison",
    compareType: "refinance-comparison",
    targetRateType: "variable",
    cancerInsuranceTarget: "ガン団信 +0.1%",
    note: "ガン団信は金利タイプの利率に年0.1%上乗せとして扱う",
  },
  {
    id: "sonybank",
    bankName: "ソニー銀行",
    productName: "住宅ローン",
    rateUrl: "https://sonybank.jp/rate/hl01.html",
    insuranceUrl: "https://sonybank.jp/products/hl/05.html",
    ratePurpose: "refinance-comparison",
    compareType: "refinance-comparison",
    targetRateType: "variable",
    cancerInsuranceTarget: "がん50上乗せなし / がん100 +0.1%",
    note: "がん50とがん100を分けて比較する",
  },
  {
    id: "rakuten",
    bankName: "楽天銀行",
    productName: "住宅ローン",
    rateUrl: "https://www.rakuten-bank.co.jp/home-loan/rate/",
    insuranceUrl: "https://www.rakuten-bank.co.jp/home-loan/insurance/all-disease.html",
    ratePurpose: "refinance-comparison",
    compareType: "refinance-comparison",
    targetRateType: "variable",
    cancerInsuranceTarget: "100%保障がん団信 +0.2%",
    note: "100%保障がん団信は年0.2%上乗せとして扱う",
  },
  {
    id: "hirogin",
    bankName: "広島銀行",
    productName: "住宅ローン",
    rateUrl: "https://www.hirogin.co.jp/service/loan/housing-loan/super/",
    insuranceUrl: "https://www.hirogin.co.jp/service/loan/housing-loan/cancer-security/",
    ratePurpose: "refinance-comparison",
    compareType: "refinance-comparison",
    targetRateType: "variable",
    cancerInsuranceTarget: "がん保障要確認",
    note: "地銀比較対象。金利優遇ページと団信ページを分けて確認する",
  },
  {
    id: "chugin",
    bankName: "中国銀行",
    productName: "住宅ローン",
    rateUrl: "https://www.chugin.co.jp/personal/service/housingloan/rate/",
    insuranceUrl: "https://www.chugin.co.jp/personal/service/housingloan/rate/",
    ratePurpose: "refinance-comparison",
    compareType: "refinance-comparison",
    targetRateType: "variable",
    cancerInsuranceTarget: "がん団信上乗せ要確認",
    note: "金利と団信条件を同一ページ内で確認する",
  },
];

*/

export const bankRateSources: BankRateSource[] = BANK_RATE_SOURCES.map((source) => ({
  ...source,
}));
