export const BANK_RATE_SOURCES = [
  {
    id: "momiji",
    bankName: "もみじ銀行",
    productName: "YCG住宅ローン（融資手数料型）",
    rateUrl: "https://www.momijibank.co.jp/personal/borrow/house/tesuuryougata/",
    insuranceUrl: "https://www.momijibank.co.jp/personal/borrow/house/tesuuryougata/",
    adapter: "official-html-diagnostic",
    referenceUrl: "https://diamond-fudosan.jp/articles/-/1111071",
    rateUrls: [
      "https://www.momijibank.co.jp/personal/borrow/house/tesuuryougata/",
      "https://www.momijibank.co.jp/personal/borrow/house/",
    ],
    aggregateAliases: ["もみじ銀行"],
    preferredKeywords: ["変動", "下限", "融資手数料型", "住宅ローン"],
    ratePurpose: "current-bank-lower-rate-check",
    compareType: "new-or-refinance-reference",
    targetRateType: "variable",
    cancerInsuranceTarget: "がん100%込み",
    note: "現在銀行。新規向け下限は交渉材料として表示し、借換え推薦には使用しない",
    expectedVariableRateRange: [0.4, 2.5],
    maxMonthlyDelta: 0.5,
  },
  {
    id: "mufg",
    bankName: "三菱UFJ銀行",
    productName: "住宅ローン",
    rateUrl: "https://www.bk.mufg.jp/kariru/jutaku/yuuguu/index.html",
    insuranceUrl: "https://www.bk.mufg.jp/kariru/jutaku/hoken/shippei/index.html",
    adapter: "official-html-diagnostic",
    referenceUrl: "https://diamond-fudosan.jp/articles/-/98183",
    kakakuCompanyCode: "008",
    rateUrls: [
      "https://www.bk.mufg.jp/kariru/jutaku/yuuguu/index.html",
      "https://www.bk.mufg.jp/kariru/jutaku/kinri/index.html",
    ],
    aggregateAliases: ["三菱UFJ銀行", "三菱UFJ"],
    preferredKeywords: ["変動", "住宅ローン", "適用金利", "借換"],
    ratePurpose: "refinance-comparison",
    compareType: "refinance-or-new-reference",
    targetRateType: "variable",
    cancerInsuranceTarget: "疾病保障プラン要確認",
    note: "公式HTMLの診断値。商品条件を確認するまで推薦対象外",
    expectedVariableRateRange: [0.4, 2.5],
    maxMonthlyDelta: 0.5,
  },
  {
    id: "smbc",
    bankName: "三井住友銀行",
    productName: "住宅ローン",
    rateUrl: "https://www.smbc.co.jp/kojin/jutaku_loan/kinri/",
    insuranceUrl: "https://www.smbc.co.jp/kojin/jutaku_loan/reason/shippei_20-46.html",
    adapter: "official-html-diagnostic",
    referenceUrl: "https://diamond-fudosan.jp/articles/-/98196",
    kakakuCompanyCode: "010",
    rateUrls: [
      "https://www.smbc.co.jp/kojin/jutaku_loan/kinri/",
      "https://www.smbc.co.jp/kojin/jutaku_loan/",
    ],
    aggregateAliases: ["三井住友銀行", "SMBC"],
    preferredKeywords: ["変動", "住宅ローン", "借換"],
    ratePurpose: "refinance-comparison",
    compareType: "refinance-comparison",
    targetRateType: "variable",
    cancerInsuranceTarget: "8大疾病保障要確認",
    note: "公式HTMLの診断値。商品条件を確認するまで推薦対象外",
    expectedVariableRateRange: [0.4, 2.5],
    maxMonthlyDelta: 0.5,
  },
  {
    id: "mizuho",
    bankName: "みずほ銀行",
    productName: "住宅ローン / 借り換え住宅ローン",
    rateUrl: "https://www.mizuhobank.co.jp/loan_housing/housingloancost/index.html",
    insuranceUrl: "https://www.mizuhobank.co.jp/loan_housing/lineup/refinanced_lineup/index.html",
    adapter: "official-html-diagnostic",
    referenceUrl: "https://diamond-fudosan.jp/articles/-/98189",
    kakakuCompanyCode: "009",
    rateUrls: [
      "https://www.mizuhobank.co.jp/loan_housing/housingloancost/index.html",
      "https://www.mizuhobank.co.jp/loan_housing/index.html",
    ],
    aggregateAliases: ["みずほ銀行", "みずほ"],
    preferredKeywords: ["変動", "住宅ローン", "金利"],
    ratePurpose: "refinance-comparison",
    compareType: "refinance-comparison",
    targetRateType: "variable",
    cancerInsuranceTarget: "要確認",
    note: "公式HTMLの診断値。商品条件を確認するまで推薦対象外",
    expectedVariableRateRange: [0.4, 2.5],
    maxMonthlyDelta: 0.5,
  },
  {
    id: "resona",
    bankName: "りそな銀行",
    productName: "住宅ローン（借り換え）",
    rateUrl: "https://www.resonabank.co.jp/kojin/jutaku/karikae/",
    insuranceUrl: "https://www.resonabank.co.jp/kojin/jutaku/karikae/",
    adapter: "official-html-diagnostic",
    referenceUrl: "https://diamond-fudosan.jp/articles/-/96233",
    kakakuCompanyCode: "013",
    rateUrls: [
      "https://www.resonabank.co.jp/kojin/jutaku/karikae/",
      "https://www.resonabank.co.jp/kojin/jutaku/kinri/",
    ],
    aggregateAliases: ["りそな銀行", "りそな"],
    preferredKeywords: ["変動", "借換", "住宅ローン"],
    ratePurpose: "refinance-comparison",
    compareType: "refinance-comparison",
    targetRateType: "variable",
    cancerInsuranceTarget: "要確認",
    note: "公式HTMLの診断値。商品条件を確認するまで推薦対象外",
    expectedVariableRateRange: [0.4, 2.5],
    maxMonthlyDelta: 0.5,
  },
  {
    id: "netbk",
    bankName: "住信SBIネット銀行",
    productName: "WEB申込コース（借換え）",
    rateUrl: "https://www.netbk.co.jp/contents/lp/homeloan/web/re.html",
    insuranceUrl: "https://www.netbk.co.jp/contents/lineup/home-loan/web/danshin/",
    adapter: "netbk-jsonp",
    referenceUrl: "https://diamond-fudosan.jp/articles/-/98041",
    kakakuCompanyCode: "001",
    apiUrl: "https://www.netbk.co.jp/contents/data/csv/kinri_hl_mr.js?callback=callbackHLMr",
    rateUrls: ["https://www.netbk.co.jp/contents/lp/homeloan/web/re.html"],
    aggregateAliases: ["住信SBIネット銀行", "住信SBI", "NEOBANK"],
    preferredKeywords: ["変動", "WEB申込", "借換"],
    ratePurpose: "refinance-comparison",
    compareType: "refinance-comparison",
    targetRateType: "variable",
    cancerInsuranceTarget: "団信プラン別上乗せ要確認",
    note: "公式JSONP。融資率80%以下/超、35年超、団信上乗せを条件判定する",
    expectedVariableRateRange: [0.5, 2.0],
    maxMonthlyDelta: 0.5,
  },
  {
    id: "jibun",
    bankName: "auじぶん銀行",
    productName: "住宅ローン",
    rateUrl: "https://www.jibunbank.co.jp/products/homeloan/interest/",
    insuranceUrl: "https://www.jibunbank.co.jp/products/homeloan/insurance/",
    adapter: "official-html-diagnostic",
    referenceUrl: "https://diamond-fudosan.jp/articles/-/98185",
    kakakuCompanyCode: "020",
    rateUrls: [
      "https://www.jibunbank.co.jp/products/homeloan/interest/",
      "https://www.jibunbank.co.jp/products/homeloan/",
    ],
    aggregateAliases: ["auじぶん銀行", "じぶん銀行"],
    preferredKeywords: ["変動", "住宅ローン", "借換"],
    ratePurpose: "refinance-comparison",
    compareType: "refinance-comparison",
    targetRateType: "variable",
    cancerInsuranceTarget: "がん50 / がん100を区別",
    note: "公式HTMLの診断値。商品条件を確認するまで推薦対象外",
    expectedVariableRateRange: [0.4, 2.5],
    maxMonthlyDelta: 0.5,
  },
  {
    id: "paypay",
    bankName: "PayPay銀行",
    productName: "住宅ローン（借換え）",
    rateUrl: "https://www.paypay-bank.co.jp/mortgage/interest/index.html",
    insuranceUrl: "https://www.paypay-bank.co.jp/mortgage/insurance/index.html",
    adapter: "paypay-api",
    referenceUrl: "https://diamond-fudosan.jp/articles/-/1110139",
    kakakuCompanyCode: "130",
    apiUrl: "https://login.paypay-bank.co.jp/wctx/MortgageRates.do",
    rateUrls: ["https://www.paypay-bank.co.jp/mortgage/interest/index.html"],
    aggregateAliases: ["PayPay銀行", "ペイペイ銀行", "PayPay"],
    preferredKeywords: ["変動", "住宅ローン", "借換"],
    ratePurpose: "refinance-comparison",
    compareType: "refinance-comparison",
    targetRateType: "variable",
    cancerInsuranceTarget: "団信プラン別上乗せ要確認",
    note: "公式公開APIの借換え・変動金利を使用。団信上乗せは別途条件確認",
    expectedVariableRateRange: [0.5, 2.0],
    maxMonthlyDelta: 0.5,
  },
  {
    id: "sbishinsei",
    bankName: "SBI新生銀行",
    productName: "住宅ローン 変動金利半年型",
    rateUrl: "https://www.sbishinseibank.co.jp/retail/housing/interest/floating/",
    insuranceUrl: "https://www.sbishinseibank.co.jp/retail/housing/insurance.html",
    adapter: "sbishinsei-api",
    referenceUrl: "https://diamond-fudosan.jp/articles/-/97674",
    kakakuCompanyCode: "004",
    apiUrl: "https://interest.sbishinseibank.co.jp/api/v1/interest_rate_hl",
    backupApiUrl: "https://bucketeer-e358148b-9fc7-449c-8826-6c073f7e6fb9.s3.amazonaws.com/public/backup/api/v1/interest_rate_hl",
    rateUrls: ["https://www.sbishinseibank.co.jp/retail/housing/interest/floating/"],
    aggregateAliases: ["SBI新生銀行", "SBI新生", "新生銀行"],
    preferredKeywords: ["変動", "住宅ローン"],
    ratePurpose: "refinance-comparison",
    compareType: "refinance-comparison",
    targetRateType: "variable",
    cancerInsuranceTarget: "ガン団信 +0.1%",
    note: "公式金利API。自己資金・SBIハイパー預金・団信条件を区別する",
    expectedVariableRateRange: [0.5, 2.0],
    maxMonthlyDelta: 0.5,
  },
  {
    id: "sonybank",
    bankName: "ソニー銀行",
    productName: "住宅ローン",
    rateUrl: "https://sonybank.jp/rate/hl01.html",
    insuranceUrl: "https://sonybank.jp/products/hl/05.html",
    adapter: "official-html-diagnostic",
    referenceUrl: "https://diamond-fudosan.jp/articles/-/98179",
    kakakuCompanyCode: "002",
    rateUrls: ["https://sonybank.jp/rate/hl01.html", "https://moneykit.net/visitor/hl/hl20.html"],
    aggregateAliases: ["ソニー銀行"],
    preferredKeywords: ["変動", "住宅ローン", "金利"],
    ratePurpose: "refinance-comparison",
    compareType: "refinance-comparison",
    targetRateType: "variable",
    cancerInsuranceTarget: "がん50上乗せなし / がん100 +0.1%",
    note: "公式HTMLの診断値。商品条件を確認するまで推薦対象外",
    expectedVariableRateRange: [0.4, 2.5],
    maxMonthlyDelta: 0.5,
  },
  {
    id: "rakuten",
    bankName: "楽天銀行",
    productName: "住宅ローン",
    rateUrl: "https://www.rakuten-bank.co.jp/home-loan/rate/",
    insuranceUrl: "https://www.rakuten-bank.co.jp/home-loan/insurance/all-disease.html",
    adapter: "official-html-diagnostic",
    referenceUrl: "https://diamond-fudosan.jp/articles/-/98173",
    kakakuCompanyCode: "007",
    rateUrls: [
      "https://www.rakuten-bank.co.jp/home-loan/rate/",
      "https://www.rakuten-bank.co.jp/home-loan/",
    ],
    aggregateAliases: ["楽天銀行"],
    preferredKeywords: ["変動", "住宅ローン", "金利"],
    ratePurpose: "refinance-comparison",
    compareType: "refinance-comparison",
    targetRateType: "variable",
    cancerInsuranceTarget: "100%保障がん団信 +0.2%",
    note: "公式HTMLの診断値。商品条件を確認するまで推薦対象外",
    expectedVariableRateRange: [0.4, 2.5],
    maxMonthlyDelta: 0.5,
  },
  {
    id: "hirogin",
    bankName: "広島銀行",
    productName: "スーパー住宅ローン",
    rateUrl: "https://www.hirogin.co.jp/service/loan/housing-loan/super/",
    insuranceUrl: "https://www.hirogin.co.jp/service/loan/housing-loan/cancer-security/",
    adapter: "hirogin-diamond",
    referenceUrl: "https://diamond-fudosan.jp/articles/-/1111034",
    rateUrls: ["https://www.hirogin.co.jp/service/loan/housing-loan/super/"],
    aggregateAliases: ["広島銀行", "ひろぎん"],
    preferredKeywords: ["変動", "住宅ローン", "借換"],
    ratePurpose: "refinance-comparison",
    compareType: "refinance-comparison",
    targetRateType: "variable",
    cancerInsuranceTarget: "がん保障要確認",
    note: "公式HTMLに金利表がないためダイヤモンド不動産の当月表を参考表示。推薦対象外",
    expectedVariableRateRange: [0.5, 2.0],
    maxMonthlyDelta: 0.5,
  },
  {
    id: "chugin",
    bankName: "中国銀行",
    productName: "住宅ローン",
    rateUrl: "https://www.chugin.co.jp/personal/service/housingloan/rate/",
    insuranceUrl: "https://www.chugin.co.jp/personal/service/housingloan/rate/",
    adapter: "official-html-diagnostic",
    referenceUrl: "https://diamond-fudosan.jp/articles/-/1111033",
    rateUrls: [
      "https://www.chugin.co.jp/personal/service/housingloan/rate/",
      "https://www.chugin.co.jp/personal/service/housingloan/",
    ],
    aggregateAliases: ["中国銀行"],
    preferredKeywords: ["変動", "住宅ローン", "金利"],
    ratePurpose: "refinance-comparison",
    compareType: "refinance-comparison",
    targetRateType: "variable",
    cancerInsuranceTarget: "がん団信上乗せ要確認",
    note: "公式HTMLの診断値。商品条件を確認するまで推薦対象外",
    expectedVariableRateRange: [0.4, 2.5],
    maxMonthlyDelta: 0.5,
  },
];

export function getBankRateSource(id) {
  return BANK_RATE_SOURCES.find((source) => source.id === id);
}
